import { Song } from './types';

export const initialSongs: Song[] = [
  {
    id: 'walk-foo-fighters',
    title: 'Walk',
    artist: 'Foo Fighters',
    album: 'Wasting Light',
    bpm: 152,
    timeSignature: '4/4',
    sections: [
      { id: 'w1', name: 'Intro (Riff A)', bars: 4, startTime: '00:00', notes: '[CHORDS] A5 | Bm\n[INSTR] Clean guitar theme (Riff A).\n[DYN] Piano - Sparse and atmospheric.', color: 'bg-zinc-800' },
      { id: 'w2', name: 'Section A1 (Verse 1a)', bars: 8, startTime: '00:06', notes: '[CHORDS] A5 | E5 | Bm | Dm\n[LYRIC] A million miles away / Your signal in the distance / To whom it may concern\n[INSTR] Clean guitar continues + Subtle bass entry.\n[DYN] Mezzo-piano.', color: 'bg-blue-900/40' },
      { id: 'w3', name: 'Section A2 (Verse 1b)', bars: 8, startTime: '00:19', notes: '[CHORDS] A5 | E5 | Bm | Dm\n[LYRIC] I think I lost my way / Getting good at starting over / Everytime that I return\n[INSTR] Full band enters. Snare on 2 and 4.\n[GROOVE] Driving 4/4 Rock.\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 'w4', name: 'Section B1 (Chorus 1a)', bars: 8, startTime: '00:31', notes: '[CHORDS] A5 | E5 | Bm | Dm\n[LYRIC] I\'m learning to walk again / I believe I\'ve waited long enough / Where do I begin?\n[INSTR] Guitars start to break up.\n[DYN] Crescendo building.', color: 'bg-red-900/40' },
      { id: 'w5', name: 'Section B2 (Chorus 1b)', bars: 8, startTime: '00:44', notes: '[CHORDS] A5 | E5 | Bm | Dm | A\n[LYRIC] I\'m learning to talk again / Can\'t you see I\'ve waited long enough / Where do I begin?\n[INSTR] Heavy distortion. Thick wall of sound.\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w6', name: 'Interlude (Riff A)', bars: 4, startTime: '00:56', notes: '[CHORDS] A5 | Bm\n[INSTR] Heavy Riff A. Drums maintain energy.\n[DYN] Forte.', color: 'bg-zinc-800' },
      { id: 'w7', name: 'Section A3 (Verse 2)', bars: 16, startTime: '01:03', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] Do you remember the days / We built these paper mountains and sat and watched them burn / I think I found my place / Can\'t you feel it growing stronger / Little conquerors\n[INSTR] Full band (heavy). Driving rhythm.\n[DYN] Forte.', color: 'bg-blue-900/40' },
      { id: 'w8', name: 'Section B3 (Chorus 2a)', bars: 8, startTime: '01:28', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m learning to walk again / I believe I\'ve waited long enough / Where do I begin?\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w9', name: 'Section B4 (Chorus 2b)', bars: 8, startTime: '01:41', notes: '[CHORDS] A | E | Bm | Dm | A\n[LYRIC] I\'m learning to talk again / I believe I\'ve waited long enough / Where do I begin?\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w10', name: 'Interlude (Riff A)', bars: 4, startTime: '01:53', notes: '[CHORDS] A5 | Bm\n[INSTR] Transition to Bridge. Drums drop to kick/snare pulse.\n[DYN] Decrescendo.', color: 'bg-zinc-800' },
      { id: 'w11', name: 'Section C1 (Bridge 1)', bars: 16, startTime: '02:00', notes: '[CHORDS] A | E | F#m | D | Dm\n[LYRIC] Now / For the very first time / Don\'t you pay no mind / Set me free again\n[INSTR] Bass pedal point. Clean guitar arpeggios.\n[DYN] Piano - Very intimate.', color: 'bg-purple-900/40' },
      { id: 'w12', name: 'Section C2 (Bridge 2)', bars: 16, startTime: '02:25', notes: '[CHORDS] A | E | F#m | D | Dm\n[LYRIC] You keep alive a moment at a time / But still inside a whisper to a riot / To sacrifice but knowing to survive / The first to climb another state of mind\n[INSTR] Drums building (toms/snare rolls).\n[DYN] Mezzo-forte building.', color: 'bg-purple-900/40' },
      { id: 'w13', name: 'Section C3 (Bridge 3)', bars: 16, startTime: '02:50', notes: '[CHORDS] A | E | F#m | D | Dm\n[LYRIC] I\'m on my knees, I\'m praying for a sign / Forever, whenever, I never wanna die\n[INSTR] Maximum intensity. Screams.\n[DYN] Fortissimo.', color: 'bg-purple-900/40' },
      { id: 'w14', name: 'Section D (Solo)', bars: 16, startTime: '03:15', notes: '[CHORDS] A | E | F#m | D | Dm\n[INSTR] Guitar Solo over Bridge progression.\n[GROOVE] Double time feel in drums.\n[DYN] Fortissimo.', color: 'bg-orange-900/40' },
      { id: 'w15', name: 'Section E1 (Chorus 3a)', bars: 8, startTime: '03:41', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I never wanna die, I never wanna die\n[DYN] Fortissimo.', color: 'bg-red-900/40' },
      { id: 'w16', name: 'Section E2 (Chorus 3b)', bars: 8, startTime: '03:53', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m on my knees, I never wanna die\n[DYN] Fortissimo.', color: 'bg-red-900/40' },
      { id: 'w17', name: 'Section E3 (Chorus 3c)', bars: 8, startTime: '04:06', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m dancing on my grave, I\'m running through the fire / Forever, whenever, I never wanna die\n[DYN] Fortissimo.', color: 'bg-red-900/40' },
      { id: 'w18', name: 'Section E4 (Chorus 3d)', bars: 8, startTime: '04:18', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I never wanna leave, I\'ll never say goodbye / Forever, whenever, forever, whenever\n[DYN] Fortissimo.', color: 'bg-red-900/40' },
      { id: 'w19', name: 'Section B5 (Chorus 4a)', bars: 8, startTime: '04:31', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m learning to walk again / I believe I\'ve waited long enough / Where do I begin?\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w20', name: 'Section B6 (Chorus 4b)', bars: 8, startTime: '04:43', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m learning to talk again / Can\'t you see I\'ve waited long enough / Where do I begin?\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w21', name: 'Section B7 (Chorus 4c)', bars: 8, startTime: '04:56', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m learning to walk again / I believe I\'ve waited long enough\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w22', name: 'Section B8 (Chorus 4d)', bars: 8, startTime: '05:08', notes: '[CHORDS] A | E | Bm | Dm\n[LYRIC] I\'m learning to talk again / Can\'t you see I\'ve waited long enough?\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'w23', name: 'Outro (Riff A)', bars: 12, startTime: '05:21', notes: '[CHORDS] A5 | Bm\n[INSTR] Final hits. Sudden stop on last beat.\n[DYN] Fortissimo to silence.', color: 'bg-zinc-800' },
    ]
  },
  {
    id: 'samurai-djavan',
    title: 'Samurai',
    artist: 'Djavan',
    album: 'Luz',
    bpm: 114,
    timeSignature: '4/4',
    sections: [
      { id: 's1', name: 'Intro (Riff A)', bars: 8, startTime: '00:00', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9) | E7M | Gº | G#m7 | B7(13) | B7(2)\n[INSTR] Main Riff (A Major 7/9) + Harmonica Theme.\n[GROOVE] Funky MPB / Sophisti-pop.\n[DYN] Mezzo-forte.', color: 'bg-zinc-800' },
      { id: 's2', name: 'Section A1 (Verse 1a)', bars: 8, startTime: '00:16', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9)\n[LYRIC] Ai / Quanto querer / Cabe em meu coração / Ai / Me faz sofrer / Faz que me mata / E se não mata, fere\n[INSTR] Funky bassline + light percussion.\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 's3', name: 'Section A2 (Verse 1b)', bars: 8, startTime: '00:33', notes: '[CHORDS] E7M | Gº | G#m7 | B7(9)\n[LYRIC] Vai / Sem me dizer / Na casa da paixão / Sai / Quando bem quer / Traz uma praga / E me afaga a pele\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 's4', name: 'Section B1 (Chorus 1)', bars: 16, startTime: '00:50', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9) | A7M | G7M | F#m7 | B7(9)\n[LYRIC] Crescei, luar / Pra iluminar as trevas / Fundas da paixão / Eu quis lutar / Contra o poder do amor / Caí nos pés do vencedor\n[INSTR] Vocal harmonies + Brass accents.\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 's5', name: 'Section C1 (Hook 1)', bars: 8, startTime: '01:24', notes: '[CHORDS] C#7(9) | G#m7 | C#7(9) | A7M | E7M | Gº | G#m7\n[LYRIC] Para ser o serviçal / Do samurai / Mas eu to\' tão feliz / Dizem que o amor atrai\n[DYN] Forte.', color: 'bg-amber-900/40' },
      { id: 's6', name: 'Section A3 (Verse 2a)', bars: 8, startTime: '01:41', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9)\n[LYRIC] Ai / Quanto querer / Cabe em meu coração / Ai / Me faz sofrer / Faz que me mata / E se não mata, fere\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 's7', name: 'Section A4 (Verse 2b)', bars: 8, startTime: '01:57', notes: '[CHORDS] E7M | Gº | G#m7 | B7(9)\n[LYRIC] Vai / Sem me dizer / Na casa da paixão / Sai / Quando bem quer / Traz uma praga / E me afaga a pele\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 's8', name: 'Section B2 (Chorus 2)', bars: 16, startTime: '02:14', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9) | A7M | G7M | F#m7 | B7(9)\n[LYRIC] Crescei, luar / Pra iluminar as trevas / Fundas da paixão / Eu quis lutar / Contra o poder do amor / Caí nos pés do vencedor\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 's9', name: 'Section C2 (Hook 2)', bars: 8, startTime: '02:48', notes: '[CHORDS] C#7(9) | G#m7 | C#7(9) | A7M | E7M | Gº | G#m7\n[LYRIC] Para ser o serviçal / Do samurai / Mas eu to\' tão feliz / Dizem que o amor atrai\n[DYN] Forte.', color: 'bg-amber-900/40' },
      { id: 's10', name: 'Solo', bars: 16, startTime: '03:05', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9) | A7M | G7M | F#m7 | B7(9)\n[INSTR] Harmonica Solo (Stevie Wonder).\n[GROOVE] Solid groove, keep it steady.\n[DYN] Forte.', color: 'bg-orange-900/40' },
      { id: 's11', name: 'Outro (Vamp)', bars: 24, startTime: '03:38', notes: '[CHORDS] E7M | Gº | G#m7 | C#7(9)\n[INSTR] Groove + Ad-libs.\n[DYN] Fade out.', color: 'bg-zinc-800' },
    ]
  },
  {
    id: 'take-on-me-aha',
    title: 'Take on Me',
    artist: 'a-ha',
    album: 'Hunting High and Low',
    bpm: 169,
    timeSignature: '4/4',
    sections: [
      { id: 't1', name: 'Intro (Riff A)', bars: 8, startTime: '00:00', notes: '[CHORDS] Bm9 | Bm | E | A | D | D/C#\n[INSTR] Main Synth Theme.\n[GROOVE] 80s Synth-pop / Electronic drums.\n[DYN] Forte.', color: 'bg-zinc-800' },
      { id: 't2', name: 'Section A1 (Verse 1)', bars: 16, startTime: '00:11', notes: '[CHORDS] Bm | E | A | D | D/C#\n[LYRIC] We\'re talking away / I don\'t know what I\'m to say / I\'ll say it anyway / Today is another day to find you / Shyin\' away / Oh, I\'ll be comin\' for your love, okay\n[INSTR] Steady electronic beat. Synth pads.\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 't3', name: 'Section B1 (Chorus 1)', bars: 16, startTime: '00:34', notes: '[CHORDS] A | E/G# | F#m | D\n[LYRIC] Take on me (take on me) / Take me on (take on me) / I\'ll be gone / In a day or two\n[INSTR] High synth lead. Driving bass.\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 't4', name: 'Interlude (Riff A)', bars: 4, startTime: '00:56', notes: '[CHORDS] Bm | E | A | D | D/C#\n[INSTR] Short Synth Theme.\n[DYN] Forte.', color: 'bg-zinc-800' },
      { id: 't5', name: 'Section A2 (Verse 2)', bars: 16, startTime: '01:02', notes: '[CHORDS] Bm | E | A | D | D/C#\n[LYRIC] So needless to say / I\'m odds and ends / But I\'ll be stumblin\' away / Slowly learnin\' that life is okay / Say after me / It\'s no better to be safe than sorry\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 't6', name: 'Section B2 (Chorus 2)', bars: 16, startTime: '01:25', notes: '[CHORDS] A | E/G# | F#m | D\n[LYRIC] Take on me (take on me) / Take me on (take on me) / I\'ll be gone / In a day or two\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 't7', name: 'Section C (Solo)', bars: 8, startTime: '01:47', notes: '[CHORDS] Bm | E | A | D | D/C#\n[INSTR] Synth Solo.\n[DYN] Forte.', color: 'bg-orange-900/40' },
      { id: 't8', name: 'Section D (Bridge)', bars: 16, startTime: '01:59', notes: '[CHORDS] Bm | E | A | D | D/C#\n[LYRIC] All the things that you say, yeah / Is it life or just to play my worries away? / You\'re all the things I\'ve got to remember / You\'re shyin\' away / I\'ll be comin\' for you anyway\n[DYN] Mezzo-forte.', color: 'bg-purple-900/40' },
      { id: 't9', name: 'Section B3 (Chorus 3)', bars: 16, startTime: '02:21', notes: '[CHORDS] A | E/G# | F#m | D\n[LYRIC] Take on me (take on me) / Take me on (take on me) / I\'ll be gone / In a day\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 't10', name: 'Section B4 (Chorus 4)', bars: 16, startTime: '02:44', notes: '[CHORDS] A | E/G# | F#m | D\n[LYRIC] (Take on me) / (Take on me) / (Take me on) / (Take on me) / I\'ll be gone / (Take on me) / In a day\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 't11', name: 'Outro (Riff A)', bars: 16, startTime: '03:07', notes: '[CHORDS] A | E/G# | F#m | D\n[LYRIC] (Take on me) / (Take on me) / (Take me on) / (Take on me) / I\'ll be gone / (Take on me) / In a day / (Take me on) / (Take on me)\n[INSTR] Final Synth Theme.\n[DYN] Fade out.', color: 'bg-zinc-800' },
    ]
  },
  {
    id: 'you-oughta-know-alanis',
    title: 'You Oughta Know',
    artist: 'Alanis Morissette',
    album: 'Jagged Little Pill',
    bpm: 105,
    timeSignature: '4/4',
    sections: [
      { id: 'y1', name: 'Section A1 (Verse 1a)', bars: 8, startTime: '00:00', notes: '[CHORDS] F#m | B\n[LYRIC] I want you to know, that I\'m happy for you / I wish nothing but the best for you both\n[INSTR] Bass & Vocal only. Clean and dry.\n[GROOVE] Minimalist funky bass.\n[DYN] Mezzo-piano.', color: 'bg-blue-900/40' },
      { id: 'y2', name: 'Section A2 (Verse 1b)', bars: 8, startTime: '00:18', notes: '[CHORDS] F#m | B\n[LYRIC] An older version of me / Is she perverted like me? / Would she go down on you in a theatre? / Does she speak eloquently / And would she have your baby? / I\'m sure she\'d make a really excellent mother\n[INSTR] Drums enter (kick/snare). Guitars start to swell.\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 'y3', name: 'Section C1 (Pre-Chorus 1)', bars: 8, startTime: '00:36', notes: '[CHORDS] F#m | A | B\n[LYRIC] \'Cause the love that you gave, that we made / Wasn\'t able to make it enough / For you to be open wide, no / And every time you speak her name / Does she know how you told me you\'d hold me / Until you died, \'til you died? / But you\'re still alive\n[INSTR] Guitars more present. Building intensity.\n[DYN] Mezzo-forte building.', color: 'bg-amber-900/40' },
      { id: 'y4', name: 'Section B1 (Chorus 1)', bars: 8, startTime: '00:54', notes: '[CHORDS] F# | E | A | B\n[LYRIC] And I\'m here to remind you / Of the mess you left when you went away / It\'s not fair to deny me / Of the cross I bear that you gave to me / You, you, you oughta know\n[INSTR] Explosive distortion. Heavy drums.\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'y5', name: 'Interlude 1', bars: 4, startTime: '01:13', notes: '[CHORDS] F# | E | A | B\n[INSTR] Main Guitar Riff. Driving rhythm.\n[DYN] Forte.', color: 'bg-zinc-800' },
      { id: 'y6', name: 'Section A3 (Verse 2a)', bars: 8, startTime: '01:22', notes: '[CHORDS] F#m | B\n[LYRIC] You seem very well / Things look peaceful / I\'m not quite as well / I thought you should know\n[INSTR] Drums drop to steady beat. Bass-driven.\n[DYN] Mezzo-forte.', color: 'bg-blue-900/40' },
      { id: 'y7', name: 'Section A4 (Verse 2b)', bars: 8, startTime: '01:40', notes: '[CHORDS] F#m | B\n[LYRIC] Did you forget about me, Mr. Duplicity? / I hate to bug you in the middle of dinner / But it was a slap in the face / How quickly I was replaced / And are you thinking of me when you fuck her?\n[INSTR] Intensity builds. Guitars more present.\n[DYN] Mezzo-forte building.', color: 'bg-blue-900/40' },
      { id: 'y8', name: 'Section C2 (Pre-Chorus 2)', bars: 8, startTime: '01:58', notes: '[CHORDS] F#m | A | B\n[LYRIC] \'Cause the love that you gave, that we made / Wasn\'t able to make it enough / For you to be open wide, no / And every time you speak her name / Does she know how you told me you\'d hold me / Until you died, \'til you died? / But you\'re still alive\n[DYN] Mezzo-forte building.', color: 'bg-amber-900/40' },
      { id: 'y9', name: 'Section B2 (Chorus 2)', bars: 8, startTime: '02:17', notes: '[CHORDS] F# | E | A | B\n[LYRIC] And I\'m here to remind you / Of the mess you left when you went away / It\'s not fair to deny me / Of the cross I bear that you gave to me / You, you, you oughta know\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'y10', name: 'Section D (Bridge)', bars: 8, startTime: '02:35', notes: '[CHORDS] F#m | A | B\n[LYRIC] \'Cause the joke that you laid in the bed / That was me, and I\'m not going to fade as soon / As you close your eyes, and you know it / And everytime I scratch my nails / Down someone else\'s back, I hope you feel it / Well, can you feel it?\n[INSTR] Dynamic drop. Bass-driven groove.\n[DYN] Mezzo-piano building to Forte.', color: 'bg-purple-900/40' },
      { id: 'y11', name: 'Section B3 (Chorus 3)', bars: 8, startTime: '02:53', notes: '[CHORDS] F# | E | A | B\n[LYRIC] Well, I\'m here to remind you / Of the mess you left when you went away / It\'s not fair to deny me / Of the cross I bear that you gave to me / You, you, you oughta know\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'y12', name: 'Section B4 (Chorus 4)', bars: 8, startTime: '03:12', notes: '[CHORDS] F# | E | A | B\n[LYRIC] I\'m here to remind you / Of the mess you left when you went away / It\'s not fair to deny me / Of the cross I bear that you gave to me / You, you, you oughta know\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'y13', name: 'Outro (Vamp)', bars: 28, startTime: '03:30', notes: '[CHORDS] F# | E | A | B\n[LYRIC] You, you, you oughta know... (Vocal ad-libs)\n[INSTR] Bass groove continues. Guitars feedback/noise.\n[DYN] Fade out.', color: 'bg-zinc-800' },
    ]
  },
  {
    id: 'numb-linkin-park',
    title: 'Numb',
    artist: 'Linkin Park',
    album: 'Meteora',
    bpm: 110,
    timeSignature: '4/4',
    sections: [
      { id: 'n1', name: 'Intro', bars: 4, startTime: '00:00', notes: '[CHORDS] G5 | Eb5 | Bb5 | F5\n[INSTR] Signature synth melody.\n[DYN] Mezzo-forte.', color: 'bg-zinc-800' },
      { id: 'n2', name: 'Verse 1', bars: 8, startTime: '00:08', notes: '[CHORDS] Gm | Eb | Bb | F\n[LYRIC] I\'m tired of being what you want me to be / Feeling so faithless, lost under the surface / Don\'t know what you\'re expecting of me / Put under the pressure of walking in your shoes\n[DYN] Mezzo-piano.', color: 'bg-blue-900/40' },
      { id: 'n3', name: 'Pre-Chorus 1', bars: 8, startTime: '00:26', notes: '[CHORDS] F | Gm | Bb | Eb | F\n[LYRIC] (Caught in the undertow, just caught in the undertow) / Every step that I take is another mistake to you\n[DYN] Mezzo-forte building.', color: 'bg-amber-900/40' },
      { id: 'n4', name: 'Chorus 1', bars: 8, startTime: '00:43', notes: '[CHORDS] G5 | Eb5 | Bb5 | F5\n[LYRIC] I\'ve become so numb, I can\'t feel you there / Become so tired, so much more aware / I\'m becoming this, all I want to do / Is be more like me and be less like you\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'n5', name: 'Verse 2', bars: 8, startTime: '01:01', notes: '[CHORDS] Gm | Eb | Bb | F\n[LYRIC] Can\'t you see that you\'re smothering me? / Holding too tightly, afraid to lose control / \'Cause everything that you thought I would be / Has fallen apart right in front of you\n[DYN] Mezzo-piano.', color: 'bg-blue-900/40' },
      { id: 'n6', name: 'Pre-Chorus 2', bars: 8, startTime: '01:18', notes: '[CHORDS] F | Gm | Bb | Eb | F | Gm\n[LYRIC] (Caught in the undertow, just caught in the undertow) / Every second I waste is more than I can take\n[DYN] Mezzo-forte building.', color: 'bg-amber-900/40' },
      { id: 'n7', name: 'Chorus 2', bars: 8, startTime: '01:36', notes: '[CHORDS] G5 | Eb5 | Bb5 | F5\n[LYRIC] I\'ve become so numb, I can\'t feel you there / Become so tired, so much more aware / I\'m becoming this, all I want to do / Is be more like me and be less like you\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'n8', name: 'Bridge', bars: 8, startTime: '01:53', notes: '[CHORDS] F5 | G5 A5 Bb5 D5 Eb5 | F5 D5\n[LYRIC] And I know I may end up failing too / But I know you were just like me, with someone disappointed in you\n[DYN] Fortissimo.', color: 'bg-purple-900/40' },
      { id: 'n9', name: 'Chorus 3', bars: 16, startTime: '02:11', notes: '[CHORDS] G5 | Eb5 | Bb5 | F5\n[LYRIC] I\'ve become so numb, I can\'t feel you there / Become so tired, so much more aware / I\'m becoming this, all I want to do / Is be more like me and be less like you / I\'ve become so numb, I can\'t feel you there / I\'m tired of being what you want me to be\n[DYN] Forte.', color: 'bg-red-900/40' },
      { id: 'n10', name: 'Outro', bars: 4, startTime: '02:46', notes: '[CHORDS] G5 | Eb5 | Bb5 | F5\n[INSTR] Synth melody fades out.\n[DYN] Decrescendo.', color: 'bg-zinc-800' },
    ]
  }
];
